# ROOT CONFIGURATION
watch_stylesheet: true
watch_config: true
debug: false

# TRAY MENU KOMOREBI
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"

# BARS CONFIGURATION
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: false
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 4
      left: 6
      bottom: 0
      right: 6
    widgets:
      left:
        ["home","komorebi_workspaces","komorebi_active_layout","apps"]
      center: ["clock"]
      right: ["cava","media","whkd","weather","volume","microphone","power_menu"]

widgets:
# HOME WIDGET
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      - { title: "Yasb Config", path: "C:\\Users\\creat\\.config\\yasb" }
      system_menu: true
      power_menu: true
      blur: true

# MEDIA WIDGET
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\uf001</span> {artist}"
      label_alt: "<span>\uf001</span> {title}"
      max_field_size:
        label: 25
        label_alt: 25
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 50
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"

# ACTIVE WINDOW TITLE WIDGET
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: false

# CLOCK WIDGET
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{ %I:%M %S %p}"
      label_alt: "{ %A, %B %d, %Y}"
      timezones: []
    calendar: 
      blur: True
      round_corners: True
      round_corners_type: "normal"
      border_color: "System"
      alignment: "center"
      direction: "down"
    callbacks:
      on_left: "toggle_label"
      on_middle: "do_nothing"
      on_right: "next_timezone"

# KOMOREBI WORKSPACES WIDGET
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: ""
      label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8

# KOMOREBI ACTIVE LAYOUT WIDGET
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "Verticle Stack"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"

# WEATHER WIDGET
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "47187afa2a20476b914101340240411"
      update_interval: 600
      hide_decimal: true
      location: "USA Zimmerman, MN 55398"
      units: "imperial"
      callbacks:
        on_right: "toggle_label"
        on_left: "toggle_card"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card: 
        blur: true
        round_corners: true
        border_color: None
        alignment: "right"
        distance: 4
        icon_size: 32

# VOLUME WIDGET
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: 'normal'
        border_color: '--pink'
        alignment: 'right'
        direction: 'down'
        distance: 6
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"

# MICROPHONE WIDGET
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}%"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"

# POWER MENU WIDGET
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: True
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]

# APPS WIDGET
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "\U000f01d8", launch: "cmd /c Taskmgr" }
        - { icon: "\U000f15ff", launch: "C:\\Users\\creat\\AppData\\Local\\Vivaldi\\Application\\vivaldi.exe" }
        - { icon: "\U000f15fc", launch: "C:\\Program Files (x86)\\Webull Desktop\\Webull Desktop.exe" }

# WHKD WIDGET
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

# CAVA AUDIO VISUALIZER WIDGET
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      gradient: 1
      reverse: 0
      sensitivity: 100
      foreground: "#89b4fa"
      gradient_color_1: '#74c7ec'
      gradient_color_2: '#89b4fa'
      gradient_color_3: '#cba6f7'
      bars_number: 10
      bar_spacing: 2
      bar_width: 3
      sleep_timer: 0
      hide_empty: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
